FROM node:20-alpine AS build
WORKDIR /app
COPY ./Startup-main/package*.json ./
RUN npm install
COPY ./Startup-main ./
ENV VITE_API_BASE_URL=/api/v1
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY ./Startup-backend/nginx/nginx.conf /etc/nginx/nginx.conf
